New Account Site features
gitkraken/gitlens-docs pull request #73
Opened 2024-01-31 21:06 UTC by jkelroy

2024-02-01 18:51 UTC, vicenter-gitkraken requested changes

2024-02-01 18:51 UTC, vicenter-gitkraken commented on gitlens/gitlens-resellers.md
> +After account creation, navigate to the left user panel, select your organization, and then "Purcahse License". Then select the number of users and proceed by selecting `Buy [Subscription]`.
_Purcahse_

2024-02-01 18:51 UTC, vicenter-gitkraken commented on gitlens/gitlens-subscriptions.md
> +3. Select your organization in the left panel and select "Purcahse License" (remember you need to have a [role](/gitkraken-client/gitkraken-organization/#roles) with permission to purchase). If you i
_Purcahse_

2024-02-02 20:18 UTC, GradyGaugler requested changes
I reviewed all the text changes and they look great. Only two small things.
* Check for grammar errors, I noticed "purchase" was spelled incorrectly a few times.
* Please add a note or sentence to the new leave organization section that owners cannot leave. That they must transfer ownership first (with link to transfer ownership).

2024-02-06 20:31 UTC, merged